title: My first blog
author: iamjayeshsingh
minima : theme
email: iamjayeshsingh@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first blog


# social links
twitter_username: iamjayeshsingh
github_username:  iamjayeshsingh

show_excerpts: true # set to false to remove excerpts on the homepage
